lulhum_repartitionmedecine_home:
    path:      /home
    defaults:  { _controller: LulhumRepartitionMedecineBundle:Repartition:index } 

lulhum_repartitionmedecine_groupes:
    path: /groupes/{promotion}
    defaults: { _controller: LulhumRepartitionMedecineBundle:Repartition:groupes }
    requirements:
        promotion: DFASM1|DFASM2

lulhum_repartitionmedecine_stages_proposals:
    path: /stages/proposals
    defaults: { _controller: LulhumRepartitionMedecineBundle:Repartition:stagesProposals }

lulhum_repartitionmedecine_stages_proposals_sorted:
    path: /stages/proposals/{sort}
    defaults: { _controller: LulhumRepartitionMedecineBundle:Repartition:stagesProposals }
    requirements:
        sort: title|places|period

lulhum_repartitionmedecine_stages_suscribe:
    path: /stages/suscribe/{id}
    defaults: { _controller: LulhumRepartitionMedecineBundle:Repartition:stagesSuscribe }
    requirements:
        id: \d+

lulhum_repartitionmedecine_stages_unsuscribe:
    path: /stages/unsuscribe/{id}
    defaults: { _controller: LulhumRepartitionMedecineBundle:Repartition:stagesUnsuscribe }
    requirements:
        id: \d+

lulhum_repartitionmedecine_stages_pending:
    path: /stages/pending
    defaults: { _controller: LulhumRepartitionMedecineBundle:Repartition:stagesPending }

lulhum_repartitionmedecine_stages_accepted:
    path: /stages/accepted
    defaults: { _controller: LulhumRepartitionMedecineBundle:Repartition:stagesAccepted }

lulhum_repartitionmedecine_admin_home:
    path: /admin/home
    defaults: { _controller: LulhumRepartitionMedecineBundle:Admin:index }

lulhum_repartitionmedecine_admin_repartitiongroup_home:
    path: /admin/group/home
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminRepartitionGroup:index }

lulhum_repartitionmedecine_admin_repartitiongroup_stop:
    path: /admin/group/stop/{promotion}
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminRepartitionGroup:stop }
    requirements:
        promotion: DFASM1|DFASM2

lulhum_repartitionmedecine_admin_repartitiongroup_start:
    path: /admin/group/start/{promotion}
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminRepartitionGroup:start }
    requirements:
        promotion: DFASM1|DFASM2

lulhum_repartitionmedecine_admin_repartition_parameters:
    path: /admin/repartition/parameters
    defaults: { _controller: LulhumRepartitionMedecineBundle:Admin:repartitionParameters }

lulhum_repartitionmedecine_admin_repartitiongroup_switchuser:
    path: /admin/group/switch/user/{id}
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminRepartitionGroup:switchUser }
    requirements:
        id: \d+

lulhum_repartitionmedecine_admin_stage_categories:
    path: /admin/stages/stagecategories
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:stageCategories }

lulhum_repartitionmedecine_admin_stage_categories_new:
    path: /admin/stages/stagecategories/new
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:newStageCategory }

lulhum_repartitionmedecine_admin_stage_categories_delete:
    path: /admin/stages/stagecategories/delete/{id}
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:deleteStageCategory }
    requirements:
        id: \d+

lulhum_repartitionmedecine_admin_stage_categories_edit:
    path: /admin/stages/stagecategories/edit/{id}
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:editStageCategory }
    requirements:
        id: \d+

lulhum_repartitionmedecine_admin_stage_categories_show:
    path: /admin/stages/stagecategories/show/{id}
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:stageCategory }
    requirements:
        id: \d+

lulhum_repartitionmedecine_admin_stage_proposals:
    path: /admin/stages/stageproposals
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:stageProposals }

lulhum_repartitionmedecine_admin_stage_proposals_incategory:
    path: /admin/stages/stageproposals/category/{id}
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:stageProposalsInCategory }
    requirements:
        id: \d+

lulhum_repartitionmedecine_admin_stage_proposals_resetfilter:
    path: /admin/stages/proposals/resetfilter
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:resetStageProposalsFilter }

lulhum_repartitionmedecine_admin_stage_proposals_new:
    path: /admin/stages/stageproposals/new
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:newStageProposal }

lulhum_repartitionmedecine_admin_stage_proposals_delete:
    path: /admin/stages/stageproposals/delete/{id}
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:deleteStageProposal }
    requirements:
        id: \d+

lulhum_repartitionmedecine_admin_stage_proposals_group_add_constraint:
    path: /admin/stages/stageproposals/group/addconstraint
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:stageProposalAddConstraint }

lulhum_repartitionmedecine_admin_stage_proposals_group_start:
    path: /admin/stages/stageproposals/group/start
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:stageProposalStart }

lulhum_repartitionmedecine_admin_requirements_getform:
    path: /admin/requirements/getform
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:getRequirementForm }

lulhum_repartitionmedecine_admin_stage_proposals_edit:
    path: /admin/stages/stageproposals/edit/{id}
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:editStageProposal }
    requirements:
        id: \d+

lulhum_repartitionmedecine_admin_stage_stages:
    path: /admin/stages/stages
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:stages }

lulhum_repartitionmedecine_admin_stage_stages_inproposal:
    path: /admin/stages/stages/proposal/{id}
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:stagesInProposal }
    requirements:
        id: \d+

lulhum_repartitionmedecine_admin_stage_stages_resetfilter:
    path: /admin/stages/stages/resetfilter
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:resetStagesFilter }

lulhum_repartitionmedecine_admin_stage_stages_new:
    path: /admin/stages/stages/new
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:newStage }

lulhum_repartitionmedecine_admin_stage_stages_delete:
    path: /admin/stages/stages/delete/{id}
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:deleteStage }
    requirements:
        id: \d+

lulhum_repartitionmedecine_admin_stage_stages_group_delete:
    path: /admin/stages/stages/group/delete
    defaults: { _controller: LulhumRepartitionMedecineBundle:AdminStages:deleteStages }