services:
    lulhum_repartitionmedecine_repartition:
        class: Lulhum\RepartitionMedecineBundle\Util\Repartition
        arguments: [ @doctrine.orm.default_entity_manager, @lulhum_repartitionmedecine_stagevalidator ]
    lulhum_repartitionmedecine_stagevalidator:
        class: Lulhum\RepartitionMedecineBundle\Util\StageValidator
        arguments: [ @doctrine.orm.default_entity_manager ]
    lulhum_parameters_repository:
        class: Lulhum\RepartitionMedecineBundle\Repository\ParameterRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['LulhumRepartitionMedecineBundle:Parameter']
    lulhum_parameter_type:
        class: Lulhum\RepartitionMedecineBundle\Form\ParameterType
        tags:
            - { name: form.type, alias: lulhum_parameter_type }
        arguments: [@doctrine]