services:
    lulhum_news_repository:
        class: Lulhum\CMSBundle\Repository\SiteNewRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['LulhumCMSBundle:SiteNew']

