lulhum_user_admin_userlist:
    path: /admin/users
    defaults: { _controller: LulhumUserBundle:Admin:listUsers }

lulhum_user_admin_userlist_page:
    path: /admin/users/page/{page}
    defaults: { _controller: LulhumUserBundle:Admin:listUsers }
    requirements:
        page: \d+

lulhum_user_admin_group_changepromotion:
    path: /admin/users/groupaction/changepromotion
    defaults: { _controller: LulhumUserBundle:Admin:groupActionChangePromotion }

lulhum_user_admin_userlist_resetfilter:
    path: /admin/users/resetfilter
    defaults: { _controller: LulhumUserBundle:Admin:resetUserFilter }

lulhum_user_admin_user:
    path: /admin/user/show/{id}
    defaults: { _controller: LulhumUserBundle:Admin:showUser }
    requirements:
        userId: \d+

lulhum_user_admin_user_edit:
    path: /admin/user/edit/{id}
    defaults: { _controller: LulhumUserBundle:Admin:editUser }
    requirements:
        userId: \d+

lulhum_user_admin_user_add:
    path: /admin/user/add
    defaults: { _controller: LulhumUserBundle:Admin:addUser }

lulhum_user_admin_user_delete:
    path: /admin/user/delete/{id}
    defaults: { _controller: LulhumUserBundle:Admin:deleteUser }
    requirements:
        userId: \d+

lulhum_user_admin_user_switchadmin:
    path: /admin/user/switchadmin/{id}
    defaults: { _controller: LulhumUserBundle:Admin:switchAdmin }
    requirements:
        userId: \d+

lulhum_user_admin_groupmail:
    path: /admin/mail
    defaults: { _controller: LulhumUserBundle:Admin:groupMail }

lulhum_user_contact:
    path: /contact
    defaults: { _controller: LulhumUserBundle:Contact:contact }
